export const Types = {
  ADD_CONTRACT: 'add-contract',
  ADD_CONTRACT_REPLY: 'add-contract-reply',
  CALL_CONTRACT: 'call-contract',
  CALL_CONTRACT_REPLY: 'call-contract-reply',
  DEPLOY_CONTRACT: 'deploy-contract',
  DEPLOY_CONTRACT_REPLY: 'deploy-contract-reply',
  IMPORT_CONTRACT: 'import-contract',
  NODE_ALL_DONE: 'node-all-done',
  NODE_CONNECTED: 'node-connected',
  NODE_STATE_CHANGE: 'node-state-change',
  NODE_SYNCING: 'node-syncing',
  NODE_SYNC_DONE: 'node-sync-done',
  NODE_SYNC_SKIP: 'node-sync-skip',
  NODE_SYNC_STATUS: 'node-sync-status',
  SEND_TRANSACTION: 'send-transaction', // main
  SEND_TRANSACTION_REPLY: 'send-transaction-reply',
  SWITCH_LAN: 'switch-lan',
  SYNC_ACCOUNT: 'sync-account',
  SYNC_ALL_STATE: 'sync-all-state', // main
  SYNC_BLOCK_NUMBER: 'sync_block_number',
  SYNC_CONTRACT: 'sync-contract',
  SYNC_TRANSACTION: 'sync-transaction',
  UI_ACTION_CLIENTBINARYSTATUS: 'ui-action-clientbinarystatus',
  UI_ACTION_NODE_STATUS: 'ui-action-node-status',
  UI_ACTION_NODE_LOGTEXT: 'ui-action-node-logtext',
  UI_ACTION_COMPILE_SYNC: 'ui-action-compile-sync',
  UI_ACTION_COMPILE: 'ui-action-compile',
  UI_ACTION_COMPILE_REPLY: 'ui-action-compile-reply',
  OZONE_LOG_DOWNLOADED: 'ozone-log-downloaded',
  OZONE_RELAUCH: 'ozone_relauch',
  LOGIN_LOCK_SETTING: 'login_lock_setting',
  HIDE_WINDOW: 'hide_window',
  MENU_ACTION_RMDATA: 'menu_action_rmdata',
  MENU_ACTION_RMDATA_CONFIRM: 'menu_action_rmdata_confirm'
}
